[package]
name = "rust_cli_task"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust_cli_task"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
rand = "0.9.1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }